In [1]:
import numpy as np

ImportError: No module named numpy

In [2]:
a=np.array([1,2,3,4,5,5,6,6])

In [3]:
a.shape
(4,2)

(4, 2)

In [4]:
a=a.reshape(2,4)

In [5]:
a

array([[1, 2, 3, 4],
       [5, 5, 6, 6]])

In [6]:
a[0][0]=888

In [7]:
a

array([[888,   2,   3,   4],
       [  5,   5,   6,   6]])

In [8]:
a.shape

(2, 4)

In [9]:
a=np.zeros((2,4))

In [10]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
a=np.empty((2,4))

In [12]:
a

array([[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   6.97620692e-321,   7.70284472e-312,
          0.00000000e+000]])

In [13]:
a=np.full((2,2),6)

In [14]:
a

array([[6, 6],
       [6, 6]])

In [15]:
b=np.eye(4,4)

In [16]:
b

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
c=np.random.random((2,2))

In [18]:
c

array([[ 0.6059414 ,  0.18265433],
       [ 0.91713763,  0.98466641]])

In [19]:
b=np.random.random((4,4))

In [20]:
b

array([[  9.23247765e-02,   7.90014005e-01,   2.29106518e-01,
          8.21476472e-01],
       [  9.57378363e-01,   5.78932231e-01,   8.79856717e-02,
          2.86221368e-01],
       [  7.26732302e-04,   4.12587604e-01,   3.36182291e-01,
          7.26368154e-02],
       [  9.41752955e-01,   2.07013380e-01,   1.26500621e-01,
          2.27852182e-01]])

In [21]:
b[2:3,1:3]

array([[ 0.4125876 ,  0.33618229]])

In [22]:
import numpy as np

In [23]:
a=np.arange(15)

In [24]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
a=a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [27]:
b=np.arange(2,17)

In [28]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
b=b.reshape(3,5)

In [30]:
b

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [31]:
c=a+b

In [32]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
c=a*b

In [34]:
a.shape

(3, 5)

In [35]:
b.reshape(5,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [36]:
b.dot(a.reshape(5,3))

array([[150, 170, 190],
       [300, 345, 390],
       [450, 520, 590]])

In [37]:
d=np.full((12,5),100,dtype=int)
d

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [38]:
d

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

# PANDAS START HERE

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("HR.CSV",sep=",")

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.head(5)

ID      Name       Department     GEO             Role  Rising_Star  \
0   1    BRADDY       Operations      US               VP          NaN   
1   2     BORST            Sales      UK  Senior Director          NaN   
2   3  BIRDWELL          Finance  France  Senior Director          NaN   
3   4      BENT  Human Resources   China  Senior Director          NaN   
4   5     BAZAN               IT   Korea         Director          NaN   

   Will_Relocate  Critical  Trending Perf  Talent_Level  \
0              0       1.0              3             6   
1              0       NaN              3             6   
2              0       NaN              3             6   
3              0       NaN              3             6   
4              0       NaN              3             6   

                   ...                    Emp_Competitive_4  \
0                  ...                                    2   
1                  ...                                    4   
2                  ...                                    2   
3                  ...                                    5   
4                  ...                                    5   

   Emp_Competitive_5  Emp_Collaborative_1  Emp_Collaborative_2  \
0                  2                    2                    2   
1                  1                    3                    2   
2                  5                    2                    2   
3                  1                    1                    2   
4                  3                    5                    1   

   Emp_Collaborative_3  Emp_Collaborative_4  Emp_Collaborative_5  \
0                    2                    1                    5   
1                    5                    1                    5   
2                    4                    4                    4   
3                    4                    4                    1   
4                    2                    5                    4   

   Sensor_StepCount  Sensor_Heartbeat(Average/Min)  \
0              1841                             61   
1              1990                             90   
2              3193                             80   
3              3248                             77   
4              3149                             80   

   Sensor_Proximity(1-highest/10-lowest)  
0                                      9  
1                                      8  
2                                      8  
3                                      6  
4                                     10  

[5 rows x 62 columns]

In [5]:
df.columns

Index(['ID', 'Name', 'Department', 'GEO', 'Role', 'Rising_Star',
       'Will_Relocate', 'Critical', 'Trending Perf', 'Talent_Level',
       'Validated_Talent_Level', 'Percent_Remote', 'EMP_Sat_OnPrem_1',
       'EMP_Sat_OnPrem_2', 'EMP_Sat_OnPrem_3', 'EMP_Sat_OnPrem_4',
       'EMP_Sat_OnPrem_5', 'EMP_Sat_Remote_1', 'EMP_Sat_Remote_2',
       'EMP_Sat_Remote_3', 'EMP_Sat_Remote_4', 'EMP_Sat_Remote_5',
       'EMP_Engagement_1', 'EMP_Engagement_2', 'EMP_Engagement_3',
       'EMP_Engagement_4', 'EMP_Engagement_5', 'last_evaluation',
       'number_project', 'average_montly_hours', 'time_spend_company',
       'Work_accident', 'left_Company', 'CSR Factor', 'promotion_last_5years',
       'sales', 'salary', 'Gender', 'LinkedIn_Hits', 'Emp_Work_Status2',
       'Emp_Work_Status_3', 'Emp_Work_Status_4', 'Emp_Work_Status_5',
       'Emp_Identity', 'Emp_Role', 'Emp_Position', 'Emp_Title', 'Women_Leave',
       'Men_Leave', 'Emp_Competitive_1', 'Emp_Competitive_2',
       'Emp_Competitive_3',

In [6]:
df.tail(5)

ID       Name       Department        GEO       Role  Rising_Star  \
14994  14995      EARLY       Operations      Korea  Level 2-4          NaN   
14995  14996   LUNSFORD            Sales  Australia  Level 2-4          NaN   
14996  14997  GOLDSMITH          Finance      China  Level 2-4          NaN   
14997  14998      FLOOD  Human Resources         US  Level 2-4          NaN   
14998  14999       Yolo               IT   Colombia  Level 2-4          NaN   

       Will_Relocate  Critical  Trending Perf  Talent_Level  \
14994              1       NaN              3             6   
14995              1       NaN              3             6   
14996              0       NaN              3             6   
14997              0       NaN              3             6   
14998              1       NaN              3             6   

                       ...                    Emp_Competitive_4  \
14994                  ...                                    3   
14995                  ...                                    4   
14996                  ...                                    2   
14997                  ...                                    1   
14998                  ...                                    1   

       Emp_Competitive_5  Emp_Collaborative_1  Emp_Collaborative_2  \
14994                  2                    4                    2   
14995                  4                    3                    1   
14996                  4                    4                    2   
14997                  5                    2                    1   
14998                  5                    2                    1   

       Emp_Collaborative_3  Emp_Collaborative_4  Emp_Collaborative_5  \
14994                    2                    3                    1   
14995                    4                    5                    5   
14996                    3                    4                    5   
14997                    3                    5                    1   
14998                    5                    3                    1   

       Sensor_StepCount  Sensor_Heartbeat(Average/Min)  \
14994              1538                             88   
14995              1247                             89   
14996              1155                             88   
14997              1210                             86   
14998              1639                             86   

       Sensor_Proximity(1-highest/10-lowest)  
14994                                      9  
14995                                      4  
14996                                      2  
14997                                      5  
14998                                      4  

[5 rows x 62 columns]

In [7]:
df.describe()

ID  Rising_Star  Will_Relocate  Critical  Trending Perf  \
count  14999.000000         21.0   14999.000000     480.0        14999.0   
mean    7500.000000          1.0       0.499833       1.0            3.0   
std     4329.982679          0.0       0.500017       0.0            0.0   
min        1.000000          1.0       0.000000       1.0            3.0   
25%     3750.500000          1.0       0.000000       1.0            3.0   
50%     7500.000000          1.0       0.000000       1.0            3.0   
75%    11249.500000          1.0       1.000000       1.0            3.0   
max    14999.000000          1.0       1.000000       1.0            3.0   

       Talent_Level  Validated_Talent_Level  Percent_Remote  EMP_Sat_OnPrem_1  \
count       14999.0                 14999.0    14999.000000           14871.0   
mean            6.0                     6.0        0.617321               3.0   
std             0.0                     0.0        0.193841               0.0   
min             6.0                     6.0        0.400000               3.0   
25%             6.0                     6.0        0.400000               3.0   
50%             6.0                     6.0        0.800000               3.0   
75%             6.0                     6.0        0.800000               3.0   
max             6.0                     6.0        1.000000               3.0   

       EMP_Sat_OnPrem_2                  ...                    \
count      14871.000000                  ...                     
mean           2.731962                  ...                     
std            0.681369                  ...                     
min            1.000000                  ...                     
25%            3.000000                  ...                     
50%            3.000000                  ...                     
75%            3.000000                  ...                     
max            3.000000                  ...                     

       Emp_Competitive_4  Emp_Competitive_5  Emp_Collaborative_1  \
count       14999.000000       14999.000000         14999.000000   
mean            2.999067           2.987066             2.979532   
std             1.406128           1.412314             1.412579   
min             1.000000           1.000000             1.000000   
25%             2.000000           2.000000             2.000000   
50%             3.000000           3.000000             3.000000   
75%             4.000000           4.000000             4.000000   
max             5.000000           5.000000             5.000000   

       Emp_Collaborative_2  Emp_Collaborative_3  Emp_Collaborative_4  \
count         14999.000000         14999.000000         14999.000000   
mean              1.676245             2.998533             3.005200   
std               0.865230             1.410058             1.410191   
min               1.000000             1.000000             1.000000   
25%               1.000000             2.000000             2.000000   
50%               2.000000             3.000000             3.000000   
75%               2.000000             4.000000             4.000000   
max               5.000000             5.000000             5.000000   

       Emp_Collaborative_5  Sensor_StepCount  Sensor_Heartbeat(Average/Min)  \
count         14999.000000      14999.000000                   14999.000000   
mean              3.016934       3406.693246                      77.967198   
std               1.412225       1755.742272                       7.252848   
min               1.000000       1000.000000                      60.000000   
25%               2.000000       1704.500000                      75.000000   
50%               3.000000       3376.000000                      78.000000   
75%               4.000000       4893.000000                      85.000000   
max               5.000000       8500.000000                      90.000000   

       Sensor_Proximity(1-highest

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 62 columns):
ID                                       14999 non-null int64
Name                                     14997 non-null object
Department                               14999 non-null object
GEO                                      14999 non-null object
Role                                     14999 non-null object
Rising_Star                              21 non-null float64
Will_Relocate                            14999 non-null int64
Critical                                 480 non-null float64
Trending Perf                            14999 non-null int64
Talent_Level                             14999 non-null int64
Validated_Talent_Level                   14999 non-null int64
Percent_Remote                           14999 non-null float64
EMP_Sat_OnPrem_1                         14871 non-null float64
EMP_Sat_OnPrem_2                         14871 non-null float64
EMP_Sat_OnPrem

In [9]:
df["Department"]

0             Operations
1                  Sales
2                Finance
3        Human Resources
4                     IT
5              Warehouse
6             Operations
7                  Sales
8                Finance
9        Human Resources
10                    IT
11             Warehouse
12            Operations
13                 Sales
14               Finance
15       Human Resources
16                    IT
17             Warehouse
18            Operations
19                 Sales
20               Finance
21       Human Resources
22                    IT
23             Warehouse
24            Operations
25                 Sales
26               Finance
27       Human Resources
28                    IT
29             Warehouse
              ...       
14969          Warehouse
14970         Operations
14971              Sales
14972            Finance
14973    Human Resources
14974                 IT
14975          Warehouse
14976         Operations
14977              Sales


In [10]:
df_2=df.iloc[2:,1:]

In [11]:
df_2

Name       Department        GEO             Role  Rising_Star  \
2         BIRDWELL          Finance     France  Senior Director          NaN   
3             BENT  Human Resources      China  Senior Director          NaN   
4            BAZAN               IT      Korea         Director          NaN   
5             BANK        Warehouse   Colombia         Director          NaN   
6            BANAS       Operations  Australia         Director          NaN   
7             BADE            Sales     Turkey         Director          NaN   
8           AUBREY          Finance      Japan         Director          NaN   
9           ARANGO  Human Resources         UK         Director          NaN   
10          AHEARN               IT      China   Senior Manager          NaN   
11           ADDIS        Warehouse      Korea   Senior Manager          NaN   
12         ZUMWALT       Operations         UK   Senior Manager          NaN   
13           WURTH            Sales   Colombia   Senior Manager          NaN   
14            WILK          Finance      Korea   Senior Manager          NaN   
15         WIDENER  Human Resources     France   Senior Manager          NaN   
16        WAGSTAFF               IT         US   Senior Manager          NaN   
17           VELLA        Warehouse      China   Senior Manager          NaN   
18         URRUTIA       Operations         US   Senior Manager          NaN   
19     TERWILLIGER            Sales  Australia   Senior Manager          NaN   
20            TART          Finance  Australia   Senior Manager          NaN   
21        STEINMAN  Human Resources      Korea   Senior Manager          NaN   
22          STAATS               IT      China          Manager          NaN   
23           SLOAT        Warehouse      Korea          Manager          NaN   
24           RIVES       Operations  Australia          Manager          NaN   
25          RIGGLE            Sales     France          Manager          NaN   
26          REVELS          Finance     France          Manager          NaN   
27        REICHARD  Human Resources      Japan          Manager          NaN   
28        PRICKETT               IT  Australia          Manager          NaN   
29            POFF        Warehouse         US          Manager          NaN   
30          PITZER       Operations         UK          Manager          NaN   
31           PETRO            Sales   Colombia          Manager          NaN   
...            ...              ...        ...              ...          ...   
14969      AMBROSE        Warehouse      China          Manager          NaN   
14970       ZAPATA       Operations      Japan          Manager          NaN   
14971        HYATT            Sales      China          Manager          NaN   
14972     HEMPHILL          Finance     Turkey          Manager          NaN   
14973        FAULK  Human Resources         US          Manager          NaN   
14974         CALL               IT         UK          Manager          NaN   
14975         DOVE        Warehouse      Japan          Manager          NaN   
14976    BOUDREAUX       Operations      Japan          Manager          NaN   
14977       ARAGON            Sales      Korea        Level 2-4          NaN   
14978     WHITLOCK          Finance      China        Level 2-4          NaN   
14979        TREJO  Human Resources         UK        Level 2-4          NaN   
14980      TACKETT               IT      China        Level 2-4          NaN   
14981      SHEARER        Warehouse  Australia        Level 2-4          NaN   
14982      SALDANA       Operations         US        Level 2-4          NaN   
14983        HANKS            Sales      Korea        Level 2-4          NaN   
14984         GOLD          Finance      Korea        Level 2-4          NaN   
14985       DRIVER  Human Resources      Korea        Level 2-4          NaN   
14986     MCKINNON               IT         US        Level 2-4          NaN   
14987      KOE

In [25]:
df2=df[(df["Department"]=="IT" and df["GEO"]=="China")]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [24]:
df2

ID          Name Department        GEO            Role  Rising_Star  \
4          5         BAZAN         IT      Korea        Director          NaN   
10        11        AHEARN         IT      China  Senior Manager          NaN   
16        17      WAGSTAFF         IT         US  Senior Manager          NaN   
22        23        STAATS         IT      China         Manager          NaN   
28        29      PRICKETT         IT  Australia         Manager          NaN   
34        35         NICKS         IT   Colombia         Manager          NaN   
40        41        LINGLE         IT         US         Manager          NaN   
46        47        LAFOND         IT         US       Level 2-4          NaN   
52        53       HAYASHI         IT         US       Level 2-4          NaN   
58        59     FROEHLICH         IT         US       Level 2-4          NaN   
64        65         DONEY         IT         US       Level 2-4          NaN   
70        71       CROWSON         IT     France       Level 2-4          NaN   
76        77    BURLINGAME         IT      Korea       Level 2-4          NaN   
82        83   BAILLARGEON         IT      China       Level 2-4          NaN   
88        89           YEH         IT   Colombia       Level 2-4          NaN   
94        95         TRUSS         IT      Korea       Level 2-4          NaN   
100      101         SHOWS         IT     France       Level 2-4          NaN   
106      107       ROSEMAN         IT      Japan       Level 2-4          NaN   
112      113       ODANIEL         IT      Japan         Level 1          NaN   
118      119       MARONEY         IT     France         Level 1          NaN   
124      125   KWIATKOWSKI         IT     France         Level 1          NaN   
130      131       HEYWOOD         IT         UK         Level 1          NaN   
136      137        GRIECO         IT   Colombia         Level 1          NaN   
142      143          FANN         IT   Colombia        Director          NaN   
148      149       BLAKLEY         IT   Colombia  Senior Manager          NaN   
154      155         WARGO         IT      Korea  Senior Manager          NaN   
160      161      STRICKER         IT         UK         Manager          NaN   
166      167        SEAVER         IT   Colombia         Manager          NaN   
172      173         RIOUX         IT      Korea         Manager          NaN   
178      179      MULVANEY         IT      Korea         Manager          NaN   
...      ...           ...        ...        ...             ...          ...   
14824  14825          BURR         IT     Turkey         Manager          NaN   
14830  14831    HUDDLESTON         IT   Colombia         Manager          NaN   
14836  14837        OLEARY         IT     France         Manager          NaN   
14842  14843          BAIN         IT     France       Level 2-4          NaN   
14848  14849         BUSBY         IT      Korea       Level 2-4          NaN   
14854  14855       BARTLEY         IT      China       Level 2-4          NaN   
14860  14861  CHRISTIANSEN         IT   Colombia       Level 2-4          NaN   
14866  14867       CONNORS         IT     France       Level 2-4          NaN   
14872  14873       ADDISON         IT     Turkey       Level 2-4          NaN   
14878  14879      BOUCHARD         IT      Japan       Level 2-4          NaN   
14884  14885    HERRINGTON         IT         UK       Level 2-4          NaN   
14890  14891          RUDD         IT      China       Level 2-4          NaN   
14896  14897        GEIGER         IT         UK       Level 2-4          NaN   
14902  14903      ESPOSITO         IT         US       Level 2-4          NaN   
14908  14909        KEENAN         IT      Japan         Level 1          NaN   
14914  14915         ROARK         IT      Japan         Level 1          NaN   
14920  14921       WHITMAN         IT     Turkey         Level 1          NaN   
14926  14927          ROMO         IT    

In [52]:
df3=df["GEO"]


In [53]:
df3.unique()

array(['US', 'UK', 'France', 'China', 'Korea', 'Colombia', 'Australia',
       'Turkey', 'Japan'], dtype=object)

In [54]:
import numpy as np 
import pandas as pd

In [55]:
df=pd.read_csv("hr.csv")

In [56]:
df.head()


ID      Name       Department     GEO             Role  Rising_Star  \
0   1    BRADDY       Operations      US               VP          NaN   
1   2     BORST            Sales      UK  Senior Director          NaN   
2   3  BIRDWELL          Finance  France  Senior Director          NaN   
3   4      BENT  Human Resources   China  Senior Director          NaN   
4   5     BAZAN               IT   Korea         Director          NaN   

   Will_Relocate  Critical  Trending Perf  Talent_Level  \
0              0       1.0              3             6   
1              0       NaN              3             6   
2              0       NaN              3             6   
3              0       NaN              3             6   
4              0       NaN              3             6   

                   ...                    Emp_Competitive_4  \
0                  ...                                    2   
1                  ...                                    4   
2                  ...                                    2   
3                  ...                                    5   
4                  ...                                    5   

   Emp_Competitive_5  Emp_Collaborative_1  Emp_Collaborative_2  \
0                  2                    2                    2   
1                  1                    3                    2   
2                  5                    2                    2   
3                  1                    1                    2   
4                  3                    5                    1   

   Emp_Collaborative_3  Emp_Collaborative_4  Emp_Collaborative_5  \
0                    2                    1                    5   
1                    5                    1                    5   
2                    4                    4                    4   
3                    4                    4                    1   
4                    2                    5                    4   

   Sensor_StepCount  Sensor_Heartbeat(Average/Min)  \
0              1841                             61   
1              1990                             90   
2              3193                             80   
3              3248                             77   
4              3149                             80   

   Sensor_Proximity(1-highest/10-lowest)  
0                                      9  
1                                      8  
2                                      8  
3                                      6  
4                                     10  

[5 rows x 62 columns]

In [57]:
df.shape

(14999, 62)

In [58]:
right=df.iloc[:12]

In [59]:
left=df.iloc[12:]

In [60]:
right

ID      Name       Department        GEO             Role  Rising_Star  \
0    1    BRADDY       Operations         US               VP          NaN   
1    2     BORST            Sales         UK  Senior Director          NaN   
2    3  BIRDWELL          Finance     France  Senior Director          NaN   
3    4      BENT  Human Resources      China  Senior Director          NaN   
4    5     BAZAN               IT      Korea         Director          NaN   
5    6      BANK        Warehouse   Colombia         Director          NaN   
6    7     BANAS       Operations  Australia         Director          NaN   
7    8      BADE            Sales     Turkey         Director          NaN   
8    9    AUBREY          Finance      Japan         Director          NaN   
9   10    ARANGO  Human Resources         UK         Director          NaN   
10  11    AHEARN               IT      China   Senior Manager          NaN   
11  12     ADDIS        Warehouse      Korea   Senior Manager          NaN   

    Will_Relocate  Critical  Trending Perf  Talent_Level  \
0               0       1.0              3             6   
1               0       NaN              3             6   
2               0       NaN              3             6   
3               0       NaN              3             6   
4               0       NaN              3             6   
5               0       NaN              3             6   
6               1       NaN              3             6   
7               1       NaN              3             6   
8               0       NaN              3             6   
9               1       NaN              3             6   
10              0       1.0              3             6   
11              1       1.0              3             6   

                    ...                    Emp_Competitive_4  \
0                   ...                                    2   
1                   ...                                    4   
2                   ...                                    2   
3                   ...                                    5   
4                   ...                                    5   
5                   ...                                    2   
6                   ...                                    3   
7                   ...                                    1   
8                   ...                                    5   
9                   ...                                    3   
10                  ...                                    4   
11                  ...                                    1   

    Emp_Competitive_5  Emp_Collaborative_1  Emp_Collaborative_2  \
0                   2                    2                    2   
1                   1                    3                    2   
2                   5                    2                    2   
3                   1                    1                    2   
4                   3                    5                    1   
5                   3                    2                    2   
6                   2                    5                    1   
7                   2                    1                    1   
8                   1                    5                    2   
9                   4                    4                    2   
10                  5                    2                    1   
11                  5                    1                    2   

    Emp_Collaborative_3  Emp_Collaborative_4  Emp_Collaborative_5  \
0                     2                    1                    5   
1                     5                    1                    5   
2                     4                    4                    4   
3                     4                    4                    1   
4                     2                    5                    4   
5                     4                    2                    4   
6                   

In [63]:
import matplotlib


In [68]:
c=df.plot()

In [70]:
import sys

In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as pl

In [7]:
cv=pd.read_csv("indicators.csv")

In [9]:
cv

CountryName CountryCode  \
0        Arab World         ARB   
1        Arab World         ARB   
2        Arab World         ARB   
3        Arab World         ARB   
4        Arab World         ARB   
5        Arab World         ARB   
6        Arab World         ARB   
7        Arab World         ARB   
8        Arab World         ARB   
9        Arab World         ARB   
10       Arab World         ARB   
11       Arab World         ARB   
12       Arab World         ARB   
13       Arab World         ARB   
14       Arab World         ARB   
15       Arab World         ARB   
16       Arab World         ARB   
17       Arab World         ARB   
18       Arab World         ARB   
19       Arab World         ARB   
20       Arab World         ARB   
21       Arab World         ARB   
22       Arab World         ARB   
23       Arab World         ARB   
24       Arab World         ARB   
25       Arab World         ARB   
26       Arab World         ARB   
27       Arab World         ARB   
28       Arab World         ARB   
29       Arab World         ARB   
...             ...         ...   
5656428    Zimbabwe         ZWE   
5656429    Zimbabwe         ZWE   
5656430    Zimbabwe         ZWE   
5656431    Zimbabwe         ZWE   
5656432    Zimbabwe         ZWE   
5656433    Zimbabwe         ZWE   
5656434    Zimbabwe         ZWE   
5656435    Zimbabwe         ZWE   
5656436    Zimbabwe         ZWE   
5656437    Zimbabwe         ZWE   
5656438    Zimbabwe         ZWE   
5656439    Zimbabwe         ZWE   
5656440    Zimbabwe         ZWE   
5656441    Zimbabwe         ZWE   
5656442    Zimbabwe         ZWE   
5656443    Zimbabwe         ZWE   
5656444    Zimbabwe         ZWE   
5656445    Zimbabwe         ZWE   
5656446    Zimbabwe         ZWE   
5656447    Zimbabwe         ZWE   
5656448    Zimbabwe         ZWE   
5656449    Zimbabwe         ZWE   
5656450    Zimbabwe         ZWE   
5656451    Zimbabwe         ZWE   
5656452    Zimbabwe         ZWE   
5656453    Zimbabwe         ZWE   
5656454    Zimbabwe         ZWE   
5656455    Zimbabwe         ZWE   
5656456    Zimbabwe         ZWE   
5656457    Zimbabwe         ZWE   

                                             IndicatorName      IndicatorCode  \
0        Adolescent fertility rate (births per 1,000 wo...        SP.ADO.TFRT   
1        Age dependency ratio (% of working-age populat...        SP.POP.DPND   
2        Age dependency ratio, old (% of working-age po...     SP.POP.DPND.OL   
3        Age dependency ratio, young (% of working-age ...     SP.POP.DPND.YG   
4              Arms exports (SIPRI trend indicator values)     MS.MIL.XPRT.KD   
5              Arms imports (SIPRI trend indicator values)     MS.MIL.MPRT.KD   
6                     Birth rate, crude (per 1,000 people)     SP.DYN.CBRT.IN   
7                                       CO2 emissions (kt)     EN.ATM.CO2E.KT   
8                   CO2 emissions (metric tons per capita)     EN.ATM.CO2E.PC   
9        CO2 emissions from gaseous fuel consumption (%...  EN.ATM.CO2E.GF.ZS   
10       CO2 emissions from liquid fuel consumption (% ...  EN.ATM.CO2E.LF.ZS   
11         CO2 emissions from liquid fuel consumption (kt)  EN.ATM.CO2E.LF.KT   
12       CO2 emissions from solid fuel consumption (% o...  EN.ATM.CO2E.SF.ZS   
13                    Death rate, crude (per 1,000 people)     SP.DYN.CDRT.IN   
14                Fertility rate, total (births per woman)     SP.DYN.TFRT.IN   
15                           Fixed telephone subscriptions        IT.MLT.MAIN   
16          Fixed telephone subscriptions (per 100 people)     IT.MLT.MAIN.P2   
17                        Hospital beds (per 1,000 people)     SH.MED.BEDS.ZS   
18           International migrant stock (% of population)     SM.POP.TOTL.ZS   
19                      International migrant stock, total        SM.POP.TOTL   
20                Life expectancy at birth, female (years)  SP.DYN.LE00.FE.IN   
21                  Life expectancy at birth, male (yea

In [16]:
df=cv[['IndicatorName','CountryName']]

In [21]:
df

IndicatorName CountryName
0        Adolescent fertility rate (births per 1,000 wo...  Arab World
1        Age dependency ratio (% of working-age populat...  Arab World
2        Age dependency ratio, old (% of working-age po...  Arab World
3        Age dependency ratio, young (% of working-age ...  Arab World
4              Arms exports (SIPRI trend indicator values)  Arab World
5              Arms imports (SIPRI trend indicator values)  Arab World
6                     Birth rate, crude (per 1,000 people)  Arab World
7                                       CO2 emissions (kt)  Arab World
8                   CO2 emissions (metric tons per capita)  Arab World
9        CO2 emissions from gaseous fuel consumption (%...  Arab World
10       CO2 emissions from liquid fuel consumption (% ...  Arab World
11         CO2 emissions from liquid fuel consumption (kt)  Arab World
12       CO2 emissions from solid fuel consumption (% o...  Arab World
13                    Death rate, crude (per 1,000 people)  Arab World
14                Fertility rate, total (births per woman)  Arab World
15                           Fixed telephone subscriptions  Arab World
16          Fixed telephone subscriptions (per 100 people)  Arab World
17                        Hospital beds (per 1,000 people)  Arab World
18           International migrant stock (% of population)  Arab World
19                      International migrant stock, total  Arab World
20                Life expectancy at birth, female (years)  Arab World
21                  Life expectancy at birth, male (years)  Arab World
22                 Life expectancy at birth, total (years)  Arab World
23                       Merchandise exports (current US$)  Arab World
24       Merchandise exports by the reporting economy (...  Arab World
25       Merchandise exports by the reporting economy, ...  Arab World
26       Merchandise exports to developing economies in...  Arab World
27       Merchandise exports to developing economies in...  Arab World
28       Merchandise exports to developing economies in...  Arab World
29       Merchandise exports to developing economies in...  Arab World
...                                                    ...         ...
5656428               PPG, multilateral (INT, current US$)    Zimbabwe
5656429         PPG, official creditors (AMT, current US$)    Zimbabwe
5656430         PPG, official creditors (DIS, current US$)    Zimbabwe
5656431         PPG, official creditors (INT, current US$)    Zimbabwe
5656432    PPG, other private creditors (AMT, current US$)    Zimbabwe
5656433    PPG, other private creditors (DIS, current US$)    Zimbabwe
5656434    PPG, other private creditors (INT, current US$)    Zimbabwe
5656435          PPG, private creditors (AMT, current US$)    Zimbabwe
5656436          PPG, private creditors (DIS, current US$)    Zimbabwe
5656437          PPG, private creditors (INT, current US$)    Zimbabwe
5656438  Principal repayments on external debt, long-te...    Zimbabwe
5656439  Principal repayments on external debt, private...    Zimbabwe
5656440       Private credit bureau coverage (% of adults)    Zimbabwe
5656441           Procedures to build a warehouse (number)    Zimbabwe
5656442           Procedures to register property (number)    Zimbabwe
5656443               Profit tax (% of commercial profits)    Zimbabwe
5656444  Proportion of seats held by women in national ...    Zimbabwe
5656445      Public credit registry coverage (% of adults)    Zimbabwe
5656446  Source data assessment of statistical capacity...    Zimbabwe
5656447  Start-up procedures to register a business (nu...    Zimbabwe
5656448  Strength of legal rights index (0=weak to 12=s...    Zimbabwe
5656449                              Tax payments (number)    Zimbabwe
5656450          Time required to build a warehouse (days)    Zimbabwe
5656451         Time required to enforce a contract (days)    Zimbabwe
5656452            Time required to get electricity (days)    Zimbabw

In [23]:
df.shape

(5656458, 2)

In [1]:
import numpy as np

In [2]:
a=np.arange(15)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
type(a)

numpy.ndarray

In [7]:
a=a.reshape(3,5)

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
import pandas as pd

In [10]:
df=pd.DataFrame(a)

In [11]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [20]:
df.columns

RangeIndex(start=0, stop=5, step=1)

In [11]:
a="WEWILLMEETATMIDNIGHT"

In [58]:
d=""
lis=[]
key=11
for i in a:
    lis.append((ord(i)-65+key)%26)
    d+=chr(((ord(i)-65+key)%26)+65)

In [59]:
lis

[7, 15, 7, 19, 22, 22, 23, 15, 15, 4, 11, 4, 23, 19, 14, 24, 19, 17, 18, 4]

In [60]:
d

'HPHTWWXPPELEXTOYTRSE'